spring:
  application:
    name: servicio-de-descubrimiento-ha

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

---
# Para utilizar este perfil
# java -D"spring.profiles.active=nodo1" -jar target/eureka-ha-eureka-0.1.0-SNAPSHOT.jar
spring:
  config:
    activate:
      on-profile: nodo1

eureka:
  instance:
    hostname: nodo1
    metadataMap:
      zone: zona1
  client:
    serviceUrl:
      defaultZone: http://localhost:3002/eureka/,http://localhost:3003/eureka/

server:
  port: ${PORT:3001}

---
# Para utilizar este perfil
# java -D"spring.profiles.active=nodo2" -jar target/eureka-ha-eureka-0.1.0-SNAPSHOT.jar
spring:
  config:
    activate:
      on-profile: nodo2

eureka:
  instance:
    hostname: nodo2
    metadataMap:
      zone: zona2
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka/,http://localhost:3003/eureka/

server:
  port: ${PORT:3002}

---
# Para utilizar este perfil
# java -D"spring.profiles.active=nodo3" -jar target/eureka-ha-eureka-0.1.0-SNAPSHOT.jar
spring:
  config:
    activate:
      on-profile: nodo3

eureka:
  instance:
    hostname: nodo3
    metadataMap:
      zone: zona3
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka/,http://localhost:3002/eureka/

server:
  port: ${PORT:3003}