
spring:
  application:
    name: servicio-de-descubrimiento-open-feign

server:
  port: ${PORT:3000}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false


management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
