spring:
  application:
    name: servicio-de-productos-gateway
    
server:
  port: ${PORT:9100}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:3000/eureka/}

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

---
# Para utilizar este perfil
# java -D"spring.profiles.active=nodo1" -jar target/gateway-productos-0.1.0-SNAPSHOT.jar
spring:
  config:
    activate:
      on-profile: nodo1

server:  
  port: ${PORT:9101}

---
# Para utilizar este perfil
# java -D"spring.profiles.active=nodo2" -jar target/gateway-productos-0.1.0-SNAPSHOT.jar
spring:
  config:
    activate:
      on-profile: nodo2

server:  
  port: ${PORT:9102}
  
---
# Para utilizar este perfil
# java -D"spring.profiles.active=nodo3" -jar target/gateway-productos-0.1.0-SNAPSHOT.jar
spring:
  config:
    activate:
      on-profile: nodo3

server:  
  port: ${PORT:9103}