spring:
  application:
    name: gateway-gateway
  cloud:
    gateway:
      routes:
      - id: moduloClientes
        uri: lb://servicio-de-clientes-gateway
        predicates:
        - Path=/clientes/**
      - id: moduloProductos
        uri: lb://SERVICIO-DE-PRODUCTOS-GATEWAY
        predicates:
        - Path=/productos/**

server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:3000/eureka/}

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
